import Head from "next/head"
import { IoIosClose } from "react-icons/io"
import { BiSearch } from "react-icons/bi"
import ProjectCard from "../components/ProjectCard"
import { IoLogoFirebase, IoLogoReact, IoLogoVue } from "react-icons/io5"
import { SiSolidity, SiNextdotjs, SiTypescript } from "react-icons/si"
import Filters from "../components/Filters"

export default function Home() {
   const data = [
      1,
      2,
      3,
      4,
      5,
      6,
      7
   ]
   return (
      <div className="flex flex-col flex-1 items-start">
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className="p-5 rounded-lg max-w-xl border border-accent shadow shadow-accent text-accent mx-auto flex flex-col mt-10">
            <IoIosClose className="ml-auto cursor-pointer hover:text-pink-500 duration-200" size={30}/>
            <p className="mb-0.5">Dear stranger,</p>
            <p>Welcome to my portfolio website. Feel free to look around. You can use the filter buttons below this message to... well to filter out projects.</p>
            <button className="border duration-200 border-accent  ml-auto mt-2 rounded px-2 uppercase text-sm font-bold py-1 hover:bg-pink-500 hover:text-white">Dont show</button>
         </div>
         <Filters/>
         <main className="grid grid-cols-4 w-full mb-10 gap-6 px-5 mx-auto max-w-7xl">
            {data.map((d, i)=>(
               <ProjectCard
                  key={i}
               />
            ))}
         </main>
      </div>
   )
}
